spring:
  application:
    name: payments-api
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus, chaosmonkey
  endpoint:
    health:
      show-details: always
    chaosmonkey:
      enabled: true
